### ISSUE TITLE
I can't log in

### ISSUE THREAD

**Issue by Odnerka11566** [icitry/YoutubeCLI#4]
Did I skip some? I'm getting this error when running it:
`
Traceback (most recent call last):
  File "C:\Users\user\YoutubeCLI\main.py", line 40, in <module>
    main()
  File "C:\Users\user\YoutubeCLI\main.py", line 34, in main
    cli_manager.run(video_url=args.video_url)
  File "C:\Users\user\YoutubeCLI\CliManager.py", line 150, in run
    self._handle_login_flow()
  File "C:\Users\user\YoutubeCLI\CliManager.py", line 171, in _handle_login_flow
    self._service_locator.auth_manager.authenticate()
  File "C:\Users\user\YoutubeCLI\service\auth\AuthManager.py", line 45, in authenticate
    flow = InstalledAppFlow.from_client_secrets_file(
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\google_auth_oauthlib\flow.py", line 198, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: './auth/client_secret.json'
`

Am I doing something wrong?
I'm using python 3.10.1 on Windows 11.

**Comment by Impre-visible** [comment]
In the video, u can see where it generate a json file on google cloud, u need to do taht and put it in the auth folder

**Comment by icitry** [comment]
Yep, as I @Impre-visible said, you need to generate your credentials json file. Make sure you select the right scope - it's described in the AuthManager class, but I'll probably add a README section as well.
